version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.2


jobs:
  build: 
    docker:
      - image: circleci/python:3.8
      
    #working_directory: ~/repo
  
    steps:
      - checkout
      
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
          
    #   - save_cache:
    #       paths:
    #         - ./venv
    #       key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      - run:
          name: Run lint
          command: |
            . venv/bin/activate
            make lint
      

workflows:
  default:
    jobs:
      - build